### ISSUE TITLE
Move mouse while holding mouse button causes crash

### ISSUE THREAD

**Issue by JakobDev** [jwlodek/py_cui#126]
**Describe the bug**
Moving the mouse while holding the mouse button causes a crash.

**To Reproduce**
1.Create a simple hello world program like this one from the example.
```python
import py_cui

# create the CUI object. Will have a 3 by 3 grid with indexes from 0,0 to 2,2
root = py_cui.PyCUI(3, 3)

# Add a label to the center of the CUI in the 1,1 grid position
root.add_label('Hello py_cui!!!', 1, 1)

# Start/Render the CUI
root.start()
```
2. Run the program.
3. Move the mouse while holdig a mouse button.
4. This crash will happen:
```
Traceback (most recent call last):
  File "/home/jUser/hello.py", line 10, in <module>
    root.start()
  File "/usr/lib/python3.9/site-packages/py_cui/__init__.py", line 317, in start
    curses.wrapper(self._draw)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/py_cui/__init__.py", line 1543, in _draw
    _, x, y, _, _ = curses.getmouse()
_curses.error: getmouse() returned ERR
```
**Expected behavior**
No crash

**Environment**
 - OS: [Manjaro]
 - Terminal: [Konsole]
 - Version: [0.1.3]

**Comment by PabloLec** [comment]
Hi, I can't reproduce on my system.

OS: `Ubuntu 20.10`
Terminal: `terminator 1.92`
Shell : `zsh`
And py_cui version `0.1.3`

So you're just pressing left click button while moving the mouse on the hello world project and you get this error?

Can you provide the output of: `echo $TERM` ?

**Comment by JakobDev** [comment]
> So you're just pressing left click button while moving the mouse on the hello world project and you get this error?

Exactly
> Can you provide the output of: `echo $TERM` ?

xterm-256color

**Comment by jwlodek** [comment]
I also can't seem to reproduce it on Windows 10 with `cmd`. What I did find , however, is that currently something like this is handled as a massive series of mouse presses rather than a single mouse click. I am working on supporting a variety of different mouse event types instead of just "click" like it is now, which is tracked in #72.

Also, to fix any potential crashes, I think maybe something as simple as a try-except block around the mouse event read to catch curses errors and maybe just dump them in the log as `ERROR` log messages is the easiest. Then, mouse events won't be handled but at least the program won't crash.

**Comment by JakobDev** [comment]
Normal clicks are working for me. Does this change mean that normal mouse clicks will no longer work?

**Comment by jwlodek** [comment]
No, normal clicks will continue to work - unless they cause a crash, they do it will be ignored and logged

**Comment by JakobDev** [comment]
Then it would be ok for me

**Comment by jwlodek** [comment]
This has been resolved along with the addition of many new mouse functions on the v0.1.4 branch, awaiting merging
