### ISSUE TITLE
Possibility to delete color rules

### ISSUE THREAD

**Issue by samari-k** [jwlodek/py_cui#160]
Hi, I am playing around with py_cui for some time and I really like it and appreciate your work. This is my first time opening an issue so I hope, I'll do it the right way and I've not overseen something.

**Is your feature request related to a problem? Please describe.**
I'm working on a little quiz game with a scroll-menu to select the quiz and a text-box to insert the answer. I'm adding color rules on this text-box to color a right answer. I need (obviously) different color rules for different questions but only one for each. I could not find something like `delete_text_color_rule(...)` so as a workaround I actually use `answer_text_box._text_color_rules.clear()` which works fine but is not optimal, because `_text_color_rules` is a protected attribute and I guess it's not meant to be used this way.

**Describe the solution you'd like**
If there's nothing I've overseen, it would be great to have something like `delete_text_color_rule()` for the widgets so the rules can change dynamically during usage.

**Comment by jwlodek** [comment]
Hi @samari-k ! Thank's for the suggestion. You are right in that at the moment there is no way to do this without accessing the `_text_color_rules` variable directly as you mentioned. This would be a nice feature to have I think. The question becomes, should we only handle deleting all color rules (which would be trivial), or deleting individual rules, or even handling overlaps (which could get more tricky, since currently the color rules don't have any unique identifiers).

**Comment by jwlodek** [comment]
Added clear color rules function with:246f13f88dc0b4c9628be8c5961f7f1036a47eaf it will be included in the next release.
