### ISSUE TITLE
Change Color Selected Item

### ISSUE THREAD

**Issue by wdog** [jwlodek/py_cui#49]
Hi!

how can i change the color of a selected line in a `scroll_menu`?  
(and in general of a particular part of a widget? )

Bold is not enough, What I have to do if I want to use reverse colors GREEN_ON_BLACK and BLACK_ON_GREEN for example.

Can I add an object to the `scroll_menu` and use maybe `__str__` for rendering, so to have a selected object and not a string `get()` or an int `get_selected_item()` ?

thanks a lot

**Comment by jwlodek** [comment]
So the first question, at the moment the library does not give the ability to do this, though you could code it in to the renderer without too much trouble. Basically, you could add a new attribute like `selected_item_color` for the widget's class, and in the `_draw` function, check if the line number matches the selected item index, and tell the renderer to use that color instead of the standard one for that line.

The reason I haven't gotten this implemented yet is because I want to think about how to make it work reliably side-by-side with the current color rule system, though I haven't quite decided the best way to do it. I am planning to add that in one of the new versions though. 

For the second question, someone had already suggested that, and the ability to add objects to menus will be included in `v0.1.1` which should release in the next few days. The feature is already working on the v0.1.1-develop branch if you want to check it out. The original suggestion is here: https://github.com/jwlodek/py_cui/issues/45, and the commit that adds the support is here: https://github.com/jwlodek/py_cui/commit/ae5bcef0260c02517256982fc886f6391573ba65

**Comment by wdog** [comment]
So for se the second question I'll wait next release, but for the first can you provide me some more tips?

I'm trying to extend the PyCUI class and add a new method `add_scroll_menu_extra`  which add and
extended class of `ScrollMenu` with the colors I need... I'm on the right way? 

By the way why can I change color to status_bar (public) and not to title_bar (private) ?

**Comment by jwlodek** [comment]
Yeah thats what I would do. Just extend the `ScrollMenu` and override the `_draw` function, and then add a new method to an extension of the `PyCUI` class like you said. You may need some extra logic to handle cases where you have a selected item you want to color that collides with a color rule. 

As for the second point, good catch, the title bar attribute should be public as well, that will be changed in the next release as well.
