### ISSUE TITLE
Request: Slider

### ISSUE THREAD

**Issue by wdog** [jwlodek/py_cui#52]
Hi I'm new to python and I'm very happy to use your library as a learning tool

I'm currently writing a very simple app https://github.com/wdog/mini-radio-player-pycui using your library.

I've implemented a simple **Slider** and a few others things as a **updatable Labels**.

I think that would be useful if you implement some of this directly in your library.

**I know that my code is awful and very buggy**, but there are some good ideas (I hope) :smile: 

Thanks

**Comment by jwlodek** [comment]
I checked out your project, nice work! I think the slider would be a nice addition to the library. I guess we could make a new module called something like `control_widgets` for widgets like sliders and things like that. I'll make a branch and set up some boilerplate stuff that you can fork and make a pull request into.

Some things I'd ask you to add: 
* Since the slider overrides all the stuff from the label, may as well make it directly inherit from the `Widget` class.
* Split the non `_draw` and `_handle_key_press` functions into a separate class that extends `UIImplementation`. For this, you could take a look at `ScrollMenu`. This is important because it allows for code reuse in case we wanted to make a slider popup (You could make one yourself if you'd like).
* Add some unit tests for slider functions

Once those things are done and pushed to the branch, we can merge them into master and include it with one of the new releases.

I think the new folder structure could be like this:

```
E:\ProgrammingWorkspace\py_cui\py_cui>tree /F
Folder PATH listing
Volume serial number is 70D3-9F41
E:.
│   colors.py
│   debug.py
│   errors.py
│   grid.py
│   keys.py
│   popups.py
│   renderer.py
│   statusbar.py
│   ui.py
│   widgets.py
│   widget_set.py
│   __init__.py
│
└───control_widgets
        slider.py
        __init__.py
```

**Comment by wdog** [comment]
Thanks a lot for your useful tips, I'll try to do something and then create a PR 

**Done**
> Since the slider overrides all the stuff from the label, may as well make it directly inherit from the Widget class.

**Comment by jwlodek** [comment]
I added a branch and some boilerplate for this. Please pull request into it if/when you get around to it:
https://github.com/jwlodek/py_cui/tree/feature-slider-widget

**Comment by wdog** [comment]
hi I've done some work, but as I've said I'm very new to all the stuff in python.
If you have time can you check my work for the Slider?

I've also tried to create some other changes as you suggested

- inherit from Widget
- test unit
- example
  
https://github.com/wdog/py_cui

Is there a way I can write to you directly to get some clarifications?

**Comment by wdog** [comment]
next step is to move everything inside the `control_widgets`

**Comment by jwlodek** [comment]
Looks good so far. We will also want to break out some of the other functions into an extension of `UIImplementation` so that we could create a slider popup more easily. I defined the classes in `control_widgets/slider.py` already, so you should be able to just copy your code over into there. Also a function to set the slider character, but that should be super easy. 

I see that you've written some tests and an example which is good too.

**Comment by wdog** [comment]
hi @jwlodek 

I've moved the code to the new structure and added to `__init__` the `add_slider` method. 
I've updated the test file and rechecked also the example not reflects the changes.

the new method  `set_bar_char` can be used to change the char used by the bar, default id '#'

can you check and tell me what more can I do, and **if/how/when** to make **PR**

**Comment by jwlodek** [comment]
You can just select `new pull request`, and then set to merge from your slider branch to mine.  It will run CI/CD tests, and then I will review and merge.
