### ISSUE TITLE
Block Label's method set_title() doesn't change the title in the widget

### ISSUE THREAD

**Issue by EGAMAGZ** [jwlodek/py_cui#60]
**Describe the bug**
Method set_title() of block label doesn't change the title in the widget, but internally in the variables it does. You can know this because when you get the value of the title, it returns you the new value not the previous one.

**To Reproduce**
It is shown in the screenshoot of the code editor

**Expected behavior**
It is expected that when the method set_title() is called, it should change the title of the widget block label as it does with label

**Screenshots**
![imagen](https://user-images.githubusercontent.com/46827955/87205108-3f56ee00-c2cc-11ea-8c44-24c39e434b0d.png)
![imagen](https://user-images.githubusercontent.com/46827955/87205118-48e05600-c2cc-11ea-95e0-3003e3eaba2e.png)
![imagen](https://user-images.githubusercontent.com/46827955/87205131-53025480-c2cc-11ea-81d5-6ab0ba6f52c2.png)

**Environment*:*
 - OS: Microsoft Windows [Versión 10.0.18362.900]
 - Terminal: CMD, Windows Terminal (WSL - Ubuntu 20.04)

**Comment by jwlodek** [comment]
Good find. I found the problem and will be adding the fix into the v0.1.2 release. Basically the issue was the title was split into lines and saved as a different instance variable for the BlockLabel object, and that variable is used to render, but changing the title doesn't change the internal instance variable.
